# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    registries:
      - 'npm-npmjs'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '01:00'
    labels: []
    open-pull-requests-limit: 99
    ignore:
      # eslint-plugin-import does not support yet eslint 9. Disable update for now
      - dependency-name: 'eslint'
      - dependency-name: '*'
        update-types: ['version-update:semver-patch', 'version-update:semver-minor']
