name: 'Publish new version'

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Package
        options:
          - '@digabi/validation'
          - '@digabi/fetch'
      bump:
        type: choice
        description: Version bump
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

run-name: 'Publish new ${{ inputs.bump }} version of package ${{ inputs.package }}'

jobs:
  publish:
    name: Publish new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > $PWD/.npmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npx lerna run --scope ${{ inputs.package }} lint
      - run: npx lerna run --scope ${{ inputs.package }} test
      - name: Publish to npm
        run: |
          TAG=latest

          if [[ "${{ inputs.bump }}" == *pre* ]]; then
            TAG=alpha
          fi

          git config --global user.email "ci@ylioppilastutkinto.fi"
          git config --global user.name "Github CI"

          npx lerna version -m "${{ inputs.bump }} release ($TAG): ${{ inputs.package }}" --yes --force-publish=${{ inputs.package }} ${{ inputs.bump }}
          npx lerna publish --dist-tag $TAG --yes from-package
