name: 'Publish new package'

on:
  workflow_dispatch:
    inputs:
      package-name:
        type: string
        description: Package name

run-name: 'Publish new package: ${{ inputs.package-name }}'

jobs:
  publish:
    name: Publish new package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Creating a new package cannot use trusted publishing so token is needed.
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_PACKAGES_NEW_PACKAGE_TOKEN }}" > $PWD/.npmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: Setup git config
        run: |
          git config --global user.email "ci@ylioppilastutkinto.fi"
          git config --global user.name "Github CI"

      - name: Create tag
        run: |
          VERSION=$(npm version --json --workspace=${{ inputs.package-name }} | jq -r '."${{ inputs.package-name }}"')
          GIT_TAG_NAME=${{ inputs.package-name }}@$VERSION

          git tag -a $GIT_TAG_NAME -m $GIT_TAG_NAME

      - name: Publish to npm and push to git
        run: |
          npm publish --workspace=${{ inputs.package-name }}
          git push && git push --tags
